import React from 'react'

export const AboutPage = () => {
    return (
        <div className="container">
            <h2>ABOUT</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis nisl quis nisl cursus finibus quis sed urna. Proin efficitur quam ut odio laoreet elementum. Vestibulum tellus massa, mollis consequat tempus at, lacinia vestibulum neque. Donec eget fringilla ex. Pellentesque quam lectus, commodo id nisi consequat, facilisis fringilla arcu. Curabitur sed dolor sed nisl pulvinar placerat. Donec vel nisl consectetur, venenatis risus sed, consectetur augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis urna vel dui ultricies eleifend eget eget tortor. Aenean sagittis augue pellentesque feugiat blandit. Suspendisse sollicitudin, velit sed hendrerit ornare, est sem aliquam lacus, non condimentum mauris velit sit amet neque. In suscipit ex vitae turpis semper, sed sagittis felis tincidunt. Donec ultricies elit nec porta pretium. Curabitur ultrices, leo ac accumsan iaculis, enim sapien porttitor urna, ut ullamcorper libero risus elementum dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            <br/>
            Pellentesque sed consequat leo. Duis erat tortor, pharetra sit amet porttitor ut, auctor in enim. Etiam tempor tincidunt mi, nec ultrices sapien sollicitudin nec. Aenean ac justo blandit, convallis lorem nec, gravida nulla. Integer sit amet neque pretium, accumsan neque in, ultricies nibh. Ut lacinia posuere velit id euismod. Nulla placerat, felis id pellentesque pulvinar, dolor nibh placerat elit, et commodo est quam quis velit. Pellentesque sed est eu diam condimentum viverra at quis metus. Nam ornare ultricies velit in faucibus. Nunc rhoncus sit amet felis a ornare. Ut volutpat dictum semper. Aliquam in nunc sem. Vestibulum efficitur convallis dui ut rhoncus.
            <br/>
            Integer tellus risus, aliquet et elementum et, ultrices a elit. Morbi risus urna, elementum in mauris vitae, ornare fringilla nulla. Aliquam ac euismod felis. Quisque vel porttitor enim, vitae finibus augue. Proin ut lobortis tortor. Cras sed ipsum ornare, rhoncus diam eu, semper turpis. Proin finibus turpis ut nunc semper, sit amet malesuada ante egestas. Sed tempor in odio sit amet convallis. Mauris convallis diam nec scelerisque ornare. Duis accumsan, erat in fermentum bibendum, mauris mauris bibendum erat, vel porta libero ipsum fermentum neque. Integer ullamcorper eu ante ac rutrum.</p>
            <h2>OUR STORY</h2>
            <p>Pellentesque sed consequat leo. Duis erat tortor, pharetra sit amet porttitor ut, auctor in enim. Etiam tempor tincidunt mi, nec ultrices sapien sollicitudin nec. Aenean ac justo blandit, convallis lorem nec, gravida nulla. Integer sit amet neque pretium, accumsan neque in, ultricies nibh. Ut lacinia posuere velit id euismod. Nulla placerat, felis id pellentesque pulvinar, dolor nibh placerat elit, et commodo est quam quis velit. Pellentesque sed est eu diam condimentum viverra at quis metus. Nam ornare ultricies velit in faucibus. Nunc rhoncus sit amet felis a ornare. Ut volutpat dictum semper. Aliquam in nunc sem. Vestibulum efficitur convallis dui ut rhoncus.
                <br/>

            Integer tellus risus, aliquet et elementum et, ultrices a elit. Morbi risus urna, elementum in mauris vitae, ornare fringilla nulla. Aliquam ac euismod felis. Quisque vel porttitor enim, vitae finibus augue. Proin ut lobortis tortor. Cras sed ipsum ornare, rhoncus diam eu, semper turpis. Proin finibus turpis ut nunc semper, sit amet malesuada ante egestas. Sed tempor in odio sit amet convallis. Mauris convallis diam nec scelerisque ornare. Duis accumsan, erat in fermentum bibendum, mauris mauris bibendum erat, vel porta libero ipsum fermentum neque. Integer ullamcorper eu ante ac rutrum.
            <br/>
            Fusce mattis dignissim justo, quis commodo velit lacinia at. Phasellus vel tortor finibus, dapibus erat quis, convallis lacus. Mauris dictum quam quis odio porttitor laoreet. Maecenas porttitor neque in arcu maximus blandit. Etiam et est ipsum. Sed consectetur sollicitudin vestibulum. Maecenas velit nunc, ullamcorper vel ipsum nec, porttitor bibendum ex. Nulla eget mollis nunc.
            <br/>
            Curabitur nec velit id est euismod rutrum. Vivamus metus lectus, pretium at sollicitudin vel, porttitor egestas urna. In accumsan justo ac iaculis ullamcorper. Etiam consectetur, ipsum sed consequat luctus, eros eros varius nulla, quis porta ipsum purus sit amet augue. Integer et fringilla massa, at euismod nunc. Sed vitae tellus nisi. Sed ut mollis neque, et porttitor nibh. Curabitur non velit ipsum. Suspendisse tristique ante a tincidunt mattis. Integer finibus ipsum posuere, elementum eros eget, pharetra ex. Donec erat velit, consequat et turpis a, dictum posuere sem. Fusce eu lacus elementum, iaculis orci a, rutrum elit. Duis rutrum diam sit amet nisl scelerisque sollicitudin. Nullam pulvinar viverra velit in semper. In luctus varius elit, a dapibus odio vehicula sed. Etiam id quam aliquet, congue sem eget, pretium velit.</p>
        </div>
    )
}